use std::collections::HashSet;
use std::fs;

use rusqlite::OptionalExtension;
use tauri::{AppHandle, Manager, State};

use crate::db::models::SummaryType;
use crate::db::Database;

#[derive(serde::Serialize)]
pub struct ExportData {
    pub markdown: String,
    pub filename: String,
}

#[tauri::command]
pub fn export_note_markdown(
    db: State<Database>,
    note_id: String,
) -> Result<ExportData, String> {
    let conn = db.conn.lock().map_err(|e| e.to_string())?;

    // Get note
    let note: (String, Option<String>, Option<String>, String, Option<String>) = conn
        .query_row(
            "SELECT title, description, participants, started_at, ended_at FROM notes WHERE id = ?1",
            [&note_id],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?, row.get(4)?)),
        )
        .map_err(|e| e.to_string())?;

    let (title, description, participants, started_at, ended_at) = note;

    // Get transcripts
    let mut stmt = conn
        .prepare(
            "SELECT start_time, end_time, text FROM transcript_segments
             WHERE note_id = ?1 ORDER BY start_time ASC",
        )
        .map_err(|e| e.to_string())?;

    let transcripts: Vec<(f64, f64, String)> = stmt
        .query_map([&note_id], |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)))
        .map_err(|e| e.to_string())?
        .filter_map(|r| r.ok())
        .collect();

    // Get summaries
    let mut stmt = conn
        .prepare(
            "SELECT summary_type, content, created_at FROM summaries
             WHERE note_id = ?1 ORDER BY created_at DESC",
        )
        .map_err(|e| e.to_string())?;

    let summaries: Vec<(String, String, String)> = stmt
        .query_map([&note_id], |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)))
        .map_err(|e| e.to_string())?
        .filter_map(|r| r.ok())
        .collect();

    // Build markdown
    let mut md = String::new();

    // Title and metadata
    md.push_str(&format!("# {}\n\n", title));
    md.push_str(&format!("**Date:** {}\n", format_datetime(&started_at)));
    if let Some(end) = ended_at {
        md.push_str(&format!("**Duration:** {}\n", calculate_duration(&started_at, &end)));
    }
    if let Some(desc) = description {
        md.push_str(&format!("\n**Description:** {}\n", desc));
    }
    if let Some(parts) = participants {
        md.push_str(&format!("**Participants:** {}\n", parts));
    }
    md.push_str("\n---\n\n");

    // Summaries
    if !summaries.is_empty() {
        md.push_str("## AI Summaries\n\n");
        for (summary_type, content, _created_at) in &summaries {
            let type_label = match SummaryType::from_str(summary_type) {
                SummaryType::Overview => "Overview",
                SummaryType::ActionItems => "Action Items",
                SummaryType::KeyDecisions => "Key Decisions",
                SummaryType::Custom => "Custom Summary",
            };
            md.push_str(&format!("### {}\n\n{}\n\n", type_label, content));
        }
        md.push_str("---\n\n");
    }

    // Transcript
    if !transcripts.is_empty() {
        md.push_str("## Transcript\n\n");
        for (start, _end, text) in &transcripts {
            let timestamp = format_timestamp(*start);
            md.push_str(&format!("**[{}]** {}\n\n", timestamp, text.trim()));
        }
    }

    // Footer
    md.push_str("\n---\n\n");
    md.push_str("*Generated by Note67*\n");

    // Generate filename
    let safe_title = title
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == ' ' || *c == '-' || *c == '_')
        .collect::<String>()
        .replace(' ', "_");
    let filename = format!("{}.md", safe_title);

    Ok(ExportData { markdown: md, filename })
}

#[tauri::command]
pub fn save_export_to_file(
    app: AppHandle,
    content: String,
    filename: String,
) -> Result<String, String> {
    let documents_dir = app
        .path()
        .document_dir()
        .map_err(|e| e.to_string())?;

    let export_dir = documents_dir.join("Note67");
    fs::create_dir_all(&export_dir).map_err(|e| e.to_string())?;

    let file_path = export_dir.join(&filename);
    fs::write(&file_path, content).map_err(|e| e.to_string())?;

    Ok(file_path.to_string_lossy().to_string())
}

/// Export every note as a plain-markdown "vault" file (frontmatter + body +
/// ## Summary + ## Action Items) into a user-chosen folder. The DB stays the
/// source of truth; this is the portable, user-owned copy. Returns the count.
#[tauri::command]
pub fn export_notes_to_folder(db: State<Database>, folder: String) -> Result<usize, String> {
    let conn = db.conn.lock().map_err(|e| e.to_string())?;
    let dir = std::path::Path::new(&folder);
    fs::create_dir_all(dir).map_err(|e| e.to_string())?;

    let notes: Vec<(String, String, Option<String>, Option<String>, String)> = {
        let mut stmt = conn
            .prepare(
                "SELECT id, title, description, participants, started_at FROM notes
                 ORDER BY started_at DESC",
            )
            .map_err(|e| e.to_string())?;
        let rows = stmt
            .query_map([], |r| {
                Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?, r.get(4)?))
            })
            .map_err(|e| e.to_string())?
            .filter_map(|r| r.ok())
            .collect();
        rows
    };

    let mut used_names: HashSet<String> = HashSet::new();
    let mut count = 0usize;

    for (id, title, description, participants, started_at) in &notes {
        let summary: Option<String> = conn
            .query_row(
                "SELECT content FROM summaries WHERE note_id = ?1 AND summary_type = 'overview'
                 ORDER BY created_at DESC LIMIT 1",
                [id],
                |r| r.get(0),
            )
            .optional()
            .map_err(|e| e.to_string())?;

        let actions: Vec<(String, Option<String>, Option<String>, i64)> = {
            let mut stmt = conn
                .prepare(
                    "SELECT text, assignee, due_date, done FROM action_items
                     WHERE note_id = ?1 ORDER BY done ASC, sort_order ASC",
                )
                .map_err(|e| e.to_string())?;
            let rows = stmt
                .query_map([id], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?)))
                .map_err(|e| e.to_string())?
                .filter_map(|r| r.ok())
                .collect();
            rows
        };

        // Tags are best-effort — never fail an export over them.
        let tags: Vec<String> = conn
            .prepare(
                "SELECT t.name FROM tags t JOIN note_tags nt ON nt.tag_id = t.id
                 WHERE nt.note_id = ?1 ORDER BY t.name",
            )
            .and_then(|mut stmt| {
                let rows: Vec<String> = stmt
                    .query_map([id], |r| r.get::<_, String>(0))?
                    .filter_map(|r| r.ok())
                    .collect();
                Ok(rows)
            })
            .unwrap_or_default();

        let md = build_vault_markdown(
            id,
            title,
            description.as_deref(),
            participants.as_deref(),
            started_at,
            summary.as_deref(),
            &actions,
            &tags,
        );

        // Unique, filesystem-safe filename per note.
        let base = sanitize_filename(title);
        let mut name = format!("{base}.md");
        let mut n = 2;
        while used_names.contains(&name) {
            name = format!("{base}-{n}.md");
            n += 1;
        }
        used_names.insert(name.clone());

        fs::write(dir.join(&name), md).map_err(|e| e.to_string())?;
        count += 1;
    }

    Ok(count)
}

fn sanitize_filename(title: &str) -> String {
    let cleaned: String = title
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '-' || c == '_' || c == ' ' { c } else { '-' })
        .collect::<String>()
        .trim()
        .replace(' ', "-");
    if cleaned.is_empty() {
        "untitled".to_string()
    } else {
        cleaned
    }
}

#[allow(clippy::too_many_arguments)]
fn build_vault_markdown(
    id: &str,
    title: &str,
    description: Option<&str>,
    participants: Option<&str>,
    started_at: &str,
    summary: Option<&str>,
    actions: &[(String, Option<String>, Option<String>, i64)],
    tags: &[String],
) -> String {
    let mut md = String::new();

    // YAML frontmatter.
    md.push_str("---\n");
    md.push_str(&format!("id: {id}\n"));
    md.push_str(&format!("title: {}\n", yaml_escape(title)));
    md.push_str(&format!("date: {}\n", started_at));
    if let Some(p) = participants.filter(|s| !s.trim().is_empty()) {
        md.push_str(&format!("participants: {}\n", yaml_escape(p)));
    }
    if !tags.is_empty() {
        md.push_str(&format!("tags: [{}]\n", tags.join(", ")));
    }
    md.push_str("---\n\n");

    // Body (the user's notes).
    if let Some(desc) = description.filter(|s| !s.trim().is_empty()) {
        md.push_str(desc.trim());
        md.push_str("\n\n");
    }

    // Summary.
    if let Some(s) = summary.filter(|s| !s.trim().is_empty()) {
        md.push_str("## Summary\n\n");
        md.push_str(s.trim());
        md.push_str("\n\n");
    }

    // Action items as GFM checkboxes.
    if !actions.is_empty() {
        md.push_str("## Action Items\n\n");
        for (text, assignee, due, done) in actions {
            let mut line = format!("- [{}] {}", if *done != 0 { "x" } else { " " }, text.trim());
            if let Some(a) = assignee.as_ref().filter(|s| !s.trim().is_empty()) {
                line.push_str(&format!(" @{a}"));
            }
            if let Some(d) = due.as_ref().filter(|s| !s.trim().is_empty()) {
                line.push_str(&format!(" 📅{d}"));
            }
            md.push_str(&line);
            md.push('\n');
        }
        md.push('\n');
    }

    md
}

fn yaml_escape(s: &str) -> String {
    if s.contains(':') || s.contains('#') || s.contains('"') {
        format!("\"{}\"", s.replace('"', "\\\""))
    } else {
        s.to_string()
    }
}

#[tauri::command]
pub fn get_export_directory(app: AppHandle) -> Result<String, String> {
    let documents_dir = app
        .path()
        .document_dir()
        .map_err(|e| e.to_string())?;

    let export_dir = documents_dir.join("Note67");
    Ok(export_dir.to_string_lossy().to_string())
}

fn format_datetime(datetime_str: &str) -> String {
    chrono::DateTime::parse_from_rfc3339(datetime_str)
        .map(|dt| dt.format("%B %d, %Y at %H:%M").to_string())
        .unwrap_or_else(|_| datetime_str.to_string())
}

fn format_timestamp(seconds: f64) -> String {
    let total_secs = seconds as u64;
    let hours = total_secs / 3600;
    let minutes = (total_secs % 3600) / 60;
    let secs = total_secs % 60;

    if hours > 0 {
        format!("{:02}:{:02}:{:02}", hours, minutes, secs)
    } else {
        format!("{:02}:{:02}", minutes, secs)
    }
}

fn calculate_duration(start: &str, end: &str) -> String {
    let start_dt = chrono::DateTime::parse_from_rfc3339(start);
    let end_dt = chrono::DateTime::parse_from_rfc3339(end);

    match (start_dt, end_dt) {
        (Ok(s), Ok(e)) => {
            let duration = e.signed_duration_since(s);
            let hours = duration.num_hours();
            let minutes = duration.num_minutes() % 60;

            if hours > 0 {
                format!("{} hour{} {} minute{}",
                    hours,
                    if hours == 1 { "" } else { "s" },
                    minutes,
                    if minutes == 1 { "" } else { "s" }
                )
            } else {
                format!("{} minute{}", minutes, if minutes == 1 { "" } else { "s" })
            }
        }
        _ => "Unknown".to_string(),
    }
}
